[package]
name = "assert_ne"
description = "assert not equals"
version = "0.3.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
repository = "https://github.com/ashleygwilliams/assert_ne.git"
readme = "README.md"
license = "MIT"

[dependencies]
